sudo: required
services: 
  - docker

before_install:
  - docker build -t tcflux/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run tcflux/react-test npm test -- --coverage

after_success:
  - docker build -t tcflux/multi-client ./client
  - docker build -t tcflux/multi-nginx ./nginx
  - docker build -t tcflux/multi-server ./server
  - docker build -t tcflux/multi-worker ./worker
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -U "$DOCKER_ID" --password-stin
  # Push images
  - docker push tcflux/multi-client
  - docker push tcflux/multi-nginx
  - docker push tcflux/multi-server
  - docker push tcflux/multi-worker