sudo: required
services: 
  - docker

before_install:
  - docker build -t tcflux/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tcflux/react-test npm test -- --coverage

after_success:
  - docker build -t tcflux/multi-client ./client
  - docker build -t tcflux/multi-nginx ./nginx
  - docker build -t tcflux/multi-server ./server
  - docker build -t tcflux/multi-worker ./worker
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images
  - docker push tcflux/multi-client
  - docker push tcflux/multi-nginx
  - docker push tcflux/multi-server
  - docker push tcflux/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-2-582257460439
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY